export const GET_TOP_RATED = "GET_TOP_RATED";
export const GET_UPCOMMING = "GET_UPCOMMING";
export const GET_NOW_PLAYING = "GET_NOW_PLAYING";
export const ADD_FAVORITE = "ADD_FAVORITE";

export const CLEAR_TOP_RATED = "CLEAR_TOP_RATED";
export const CLEAR_UPCOMMING = "CLEAR_UPCOMMING";
export const CLEAR_NOW_PLAYING = "CLEAR_NOW_PLAYING";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
